### PR TITLE
New docker tags (v10.0, v9.2, etc) and update builts

### PR DESCRIPTION
**Pull request by lord-alfred**

### CODE REVIEW

**Comment by lord-alfred** [comment]
Hey?

**Comment by lord-alfred** [comment]
Bump

**Comment by crisbal** [comment]
Hey, sorry for not merging this early. I still don't have a machine to test these ATM so I am assuming they work. Thanks for doing this. I really appreciate it.

**Comment by lord-alfred** [comment]
@crisbal , thanks! :)
Don't worry, I tested them all on my home server.

**Pull request merged**
